<?php

declare(strict_types=1);

namespace App\Models;

use App\Domain\Affiliations\SocialSecurityEntityType;
use App\Domain\Shared\RecordStatus;
use Database\Factories\SocialSecurityEntityFactory;
use Illuminate\Database\Eloquent\Attributes\Fillable;
use Illuminate\Database\Eloquent\Attributes\Scope;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Casts\Attribute;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;

/**
 * An EPS, AFP, ARL or Caja de Compensación Familiar.
 *
 * The catalogue is populated by authorised administrators from an official
 * source. It is deliberately not seeded from a list written by hand: a stale
 * catalogue is worse than an empty one, because nothing in it would say which
 * entries were verified.
 *
 * `normalized_name` is a generated column, so it cannot drift from `name`.
 *
 * @property int $id
 * @property SocialSecurityEntityType $type
 * @property string $normalized_name
 * @property string $status
 */
#[Fillable(['type', 'name', 'code', 'tax_id', 'status'])]
class SocialSecurityEntity extends Model
{
    /** @use HasFactory<SocialSecurityEntityFactory> */
    use HasFactory;

    /**
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'type' => SocialSecurityEntityType::class,
            'status' => RecordStatus::class,
        ];
    }

    public function isActive(): bool
    {
        return $this->status === RecordStatus::Active;
    }

    /**
     * Generated by the database: exposed so the interface can render it without
     * a second request, and never written from application code.
     */
    protected function normalizedName(): Attribute
    {
        return Attribute::make(get: fn (?string $value): ?string => $value);
    }

    protected function name(): Attribute
    {
        return Attribute::make(
            set: fn (?string $value): ?string => $value === null ? null : trim($value),
        );
    }

    /**
     * @return HasMany<ClientAffiliation, $this>
     */
    public function affiliations(): HasMany
    {
        return $this->hasMany(ClientAffiliation::class);
    }

    /**
     * @return HasMany<ClientAffiliation, $this>
     */
    public function activeAffiliations(): HasMany
    {
        return $this->affiliations()->whereNull('ended_on');
    }

    /**
     * @param  Builder<self>  $query
     */
    #[Scope]
    protected function active(Builder $query): void
    {
        $query->where('status', 'active');
    }
}
