<?php

declare(strict_types=1);

use App\Domain\Receivables\ReceivablesService;
use App\Domain\Reports\Export\FormulaGuard;
use App\Domain\Reports\ReportFactory;
use App\Domain\Reports\ReportFormat;
use App\Domain\Reports\ReportGenerator;
use App\Domain\Reports\ReportScheduleRunner;
use App\Domain\Reports\ReportType;
use App\Models\Client;
use App\Models\Company;
use App\Models\GeneratedReport;
use App\Models\ReportSchedule;
use App\Models\User;
use Illuminate\Support\Facades\Notification;
use Illuminate\Support\Facades\Storage;
use Spatie\Permission\PermissionRegistrar;

beforeEach(function (): void {
    seedPortfolioRoles();

    $this->company = Company::factory()->create(['tax_id' => '900123456']);
    $this->client = Client::factory()->create();

    $this->operator = userWithPermissions(['reports.view', 'reports.export', 'reports.schedule', 'planillas.view']);
});

it('produces the morosos report from A03 receivables arithmetic', function (): void {
    // §83 / §72.31: the report must not be a second receivables formula. It asks A03 for
    // the population and reports what A03 says.
    $report = app(ReportFactory::class)->make(ReportType::Morosos, []);

    expect($report->rows())->toBeArray()
        ->and($report->columns())->not->toBeEmpty()
        ->and($report->meta()['title'])->toBe('Morosos / cartera pendiente');

    // And the numbers agree with the service it delegates to, exactly.
    $a03 = app(ReceivablesService::class)->list([], 1, 500);

    expect(count($report->rows()))->toBe(count($a03['items']));
});

it('treats due today as not overdue, because A03 decides that', function (): void {
    // §52 / §72.32: "due today != overdue". The filter is passed to A03 untouched, so
    // this milestone cannot redefine it even if it wanted to.
    $asOf = today()->toDateString();

    $overdue = app(ReportFactory::class)->make(ReportType::Vencidos, ['as_of' => $asOf]);

    expect($overdue->filters()['overdue_only'])->toBeTrue();
});

it('scopes a report to the permission its caller holds', function (): void {
    $noReports = userWithPermissions(['novelties.view']);

    $this->actingAs($noReports)->getJson('/api/reports?type=morosos')->assertForbidden();

    $this->actingAs($this->operator)->getJson('/api/reports?type=morosos')->assertOk();
});

it('escapes formula injection in every text export', function (): void {
    // §53 / §72.34. A debtor whose name begins with "=" must not become a live formula.
    expect(FormulaGuard::cell('=1+1'))->toBe("'=1+1")
        ->and(FormulaGuard::cell('@SUM(A1)'))->toBe("'@SUM(A1)")
        ->and(FormulaGuard::cell('+CMD'))->toBe("'+CMD")
        ->and(FormulaGuard::cell('-500'))->toBe("'-500")
        // Numbers are not text: a negative money figure must stay a number.
        ->and(FormulaGuard::cell(-500))->toBe(-500)
        ->and(FormulaGuard::cell('Ana María'))->toBe('Ana María');
});

it('stores a generated report privately and never exposes its path', function (): void {
    Storage::fake('local');

    $generated = app(ReportGenerator::class)->generate(
        ReportType::Morosos,
        [],
        ReportFormat::Pdf,
        $this->operator,
    );

    expect($generated->stored_path)->toStartWith('reports/')
        ->and($generated->sha256)->toHaveLength(64)
        ->and(app(ReportGenerator::class)->contents($generated))->not->toBeNull();

    // The API must publish no path.
    $response = $this->actingAs($this->operator)->getJson('/api/reports/generated')->assertOk();
    expect($response->json('data.0'))->not->toHaveKey('stored_path');
});

it('rechecks authorization when downloading an old report', function (): void {
    Storage::fake('local');

    $generated = app(ReportGenerator::class)->generate(
        ReportType::Morosos,
        [],
        ReportFormat::Pdf,
        $this->operator,
    );

    // Same user, permission intact: allowed.
    $this->actingAs($this->operator)
        ->getJson("/api/reports/generated/{$generated->id}/download")
        ->assertOk();

    // §55: losing the permission stops the download even though the file already exists
    // and was generated by that same person.
    $demoted = $this->operator->fresh();
    $demoted->syncRoles([]);
    PermissionRegistrar::class;
    app(PermissionRegistrar::class)->forgetCachedPermissions();

    $this->actingAs($demoted->fresh())
        ->getJson("/api/reports/generated/{$generated->id}/download")
        ->assertForbidden();
});

it('generates a scheduled report exactly once per occurrence', function (): void {
    Storage::fake('local');
    Notification::fake();

    $schedule = ReportSchedule::factory()->create([
        'owner_user_id' => $this->operator->id,
        'report_type' => ReportType::Morosos->value,
        'format' => ReportFormat::Pdf->value,
        'active' => true,
        'next_run_at' => now()->subMinute(),
    ]);

    $runner = app(ReportScheduleRunner::class);

    $first = $runner->runDue();
    $second = $runner->runDue();

    // §57: two ticks, one artifact.
    expect($first)->toBe(1)
        ->and($second)->toBe(0)
        ->and(GeneratedReport::query()->where('report_type', 'morosos')->count())->toBe(1);
});

it('produces nothing when the schedule owner lost the permission', function (): void {
    Storage::fake('local');
    Notification::fake();

    $schedule = ReportSchedule::factory()->create([
        'owner_user_id' => $this->operator->id,
        'report_type' => ReportType::Morosos->value,
        'format' => ReportFormat::Pdf->value,
        'active' => true,
        'next_run_at' => now()->subMinute(),
    ]);

    $demoted = $this->operator->fresh();
    $demoted->syncRoles([]);
    app(PermissionRegistrar::class)->forgetCachedPermissions();

    app(ReportScheduleRunner::class)->runDue();

    expect(GeneratedReport::query()->where('report_type', 'morosos')->count())->toBe(0);
});

it('rejects an unknown report type with a machine-readable code', function (): void {
    // §63: an unknown value for a declared input is 422, not 409 — nothing is in
    // conflict, the request simply names something that does not exist.
    $this->actingAs($this->operator)
        ->getJson('/api/reports?type=drop_everything')
        ->assertStatus(422)
        ->assertJsonPath('code', 'unknown_report_type');
});

it('exports the morosos report as csv, pdf and xlsx', function (): void {
    Storage::fake('local');

    $this->actingAs($this->operator)->getJson('/api/reports/download?type=morosos&format=csv')
        ->assertOk();

    $this->actingAs($this->operator)->getJson('/api/reports/download?type=morosos&format=pdf')
        ->assertOk();

    $this->actingAs($this->operator)->getJson('/api/reports/download?type=morosos&format=xlsx')
        ->assertOk();
});
